name = "SpinAdaptedSecondQuantization"
uuid = "07861ef0-4e5e-45a9-88ac-f5a78d3027be"
authors = ["MarcusTL12 <marcuspaafjellet@gmail.com>", "torhaugl <tor.s.haugland@ntnu.no>"]
version = "0.8.2"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Permutations = "2ae35dd2-176d-5d53-8349-f30d82d94d4f"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
DataStructures = "0.18"
Permutations = "0.4"
PrecompileTools = "1.2"
julia = "1.8"
