name = "SpinAdaptedSecondQuantization"
uuid = "07861ef0-4e5e-45a9-88ac-f5a78d3027be"
authors = ["MarcusTL12 <marcuspaafjellet@gmail.com>", "torhaugl <tor.s.haugland@ntnu.no>"]
version = "0.6.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Permutations = "2ae35dd2-176d-5d53-8349-f30d82d94d4f"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SnoopPrecompile = "66db9d55-30c0-4569-8b51-7e840670fc0c"

[compat]
DataStructures = "0.18"
Permutations = "0.4"
SnoopPrecompile = "1.0"
julia = "1.8"
